import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Plus_Jakarta_Sans } from "next/font/google";
import SideBar from "@/components/layout/SideBar";
import { Box, Flex } from "@chakra-ui/react";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakarta.variable} `}>
        <Provider>
          <Box bg="primary" display="flex" h="100vh">
            <SideBar />
            <Flex as="main" direction="column" flex={1} overflow="hidden">
              <Navbar />
              <Box
                as="main"
                flex={1}
                overflow="auto"
                bg="secondary"
                padding="30px 50px"
                display="flex"
              >
                {children}
              </Box>
            </Flex>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
